name: Bug Report
description: Report a problem in HelloWorldTimey
title: "[BUG] <description>"
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in detail.
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: "1. Go to page X\n2. Click button Y\n3. See error"
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "e.g., Windows 11, .NET 7"
